2020-01-23 16:56:35,389 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 16:57:09,250 [ERROR]  Exception occurred while handling uri: 'http://e7c0242a.ngrok.io/'
Traceback (most recent call last):
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
2020-01-23 16:57:11,393 [ERROR]  Exception occurred while handling uri: 'http://e7c0242a.ngrok.io/'
Traceback (most recent call last):
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
2020-01-23 17:26:07,411 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 17:32:28,877 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 17:32:36,940 [ERROR]  An exception occured while handling user message 'hi'.
Traceback (most recent call last):
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 459, in receive
    text, collector, sender_id, input_channel=input_channel
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 65, in handler
    await app.agent.handle_message(*args, **kwargs)
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/agent.py", line 488, in handle_message
    return await processor.handle_message(message)
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/processor.py", line 90, in handle_message
    await self._predict_and_execute_next_action(message, tracker)
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/processor.py", line 356, in _predict_and_execute_next_action
    action, tracker, message.output_channel, self.nlg, policy, confidence
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/processor.py", line 466, in _run_action
    await self._send_bot_messages(events, tracker, output_channel)
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/processor.py", line 388, in _send_bot_messages
    await output_channel.send_response(tracker.sender_id, e.message())
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 165, in send_response
    **message
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 241, in send_quick_replies
    await self.send_text_with_buttons(recipient_id, text, quick_replies, **kwargs)
TypeError: send_text_with_buttons() got multiple values for argument 'buttons'
2020-01-23 17:32:40,802 [ERROR]  An exception occured while handling user message 'hi'.
Traceback (most recent call last):
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 459, in receive
    text, collector, sender_id, input_channel=input_channel
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 65, in handler
    await app.agent.handle_message(*args, **kwargs)
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/agent.py", line 488, in handle_message
    return await processor.handle_message(message)
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/processor.py", line 90, in handle_message
    await self._predict_and_execute_next_action(message, tracker)
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/processor.py", line 356, in _predict_and_execute_next_action
    action, tracker, message.output_channel, self.nlg, policy, confidence
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/processor.py", line 466, in _run_action
    await self._send_bot_messages(events, tracker, output_channel)
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/processor.py", line 388, in _send_bot_messages
    await output_channel.send_response(tracker.sender_id, e.message())
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 165, in send_response
    **message
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 241, in send_quick_replies
    await self.send_text_with_buttons(recipient_id, text, quick_replies, **kwargs)
TypeError: send_text_with_buttons() got multiple values for argument 'buttons'
2020-01-23 18:35:29,719 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 18:40:37,849 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 18:45:15,151 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 18:50:21,799 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 18:53:23,748 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 18:54:27,837 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 18:55:14,055 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 18:56:35,038 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 18:59:29,332 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 19:00:17,074 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-23 19:13:04,833 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 19:13:50,626 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-23 19:15:05,503 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 19:15:52,222 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-23 19:31:12,869 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 19:32:00,068 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-23 19:37:46,955 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 19:38:31,397 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-23 20:24:27,312 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 20:25:16,620 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-23 20:38:13,232 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 20:39:02,402 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-23 20:51:39,872 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 20:52:26,262 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-23 20:56:22,280 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 20:57:09,056 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-23 21:01:56,074 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 21:02:53,092 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-23 21:16:11,128 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 21:16:56,760 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-23 21:20:25,203 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 21:21:13,892 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-23 21:32:40,138 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 21:33:28,530 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-23 21:53:50,718 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 21:54:39,007 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-23 22:05:16,083 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-23 22:06:04,904 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-24 10:05:27,015 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-24 10:06:14,851 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-24 10:46:37,251 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-24 10:47:36,252 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-24 10:55:34,347 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-24 10:56:10,140 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-24 11:10:39,672 [ERROR]  An exception occured while handling user message 'None'.
Traceback (most recent call last):
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 459, in receive
    text, collector, sender_id, input_channel=input_channel
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 65, in handler
    await app.agent.handle_message(*args, **kwargs)
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/agent.py", line 488, in handle_message
    return await processor.handle_message(message)
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/processor.py", line 80, in handle_message
    tracker = await self.log_message(message)
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/processor.py", line 134, in log_message
    await self._handle_message_with_tracker(message, tracker)
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/processor.py", line 302, in _handle_message_with_tracker
    parse_data = await self._parse_message(message)
  File "/home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/rasa/core/processor.py", line 280, in _parse_message
    if message.text.startswith(INTENT_MESSAGE_PREFIX):
AttributeError: 'NoneType' object has no attribute 'startswith'
2020-01-24 11:33:05,705 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-24 11:33:39,096 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-24 11:38:45,223 [DEBUG]  CORS: Configuring CORS with resources: {'/*': {'origins': [''], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': None, 'supports_credentials': False, 'max_age': None, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': {'/*': {'origins': ''}}, 'intercept_exceptions': True, 'always_send': True}}
2020-01-24 11:38:45,225 [DEBUG]  Available web server routes: 
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/webhooks/slack                                    GET                            slack_webhook.health
/webhooks/slack/webhook                            POST                           slack_webhook.webhook
2020-01-24 11:38:45,225 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-24 11:38:45,226 [INFO ]  Enabling coroutine debugging. Loop id 94533244623032.
2020-01-24 11:38:45,235 [DEBUG]  Extracted model to '/tmp/tmp86g6k5xs'.
2020-01-24 11:39:15,159 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-01-24 11:39:15,182 [DEBUG]  Connected to InMemoryTrackerStore.
2020-01-24 11:39:15,196 [DEBUG]  Extracted model to '/tmp/tmpe6v487kf'.
2020-01-24 11:39:15,200 [DEBUG]  Using yaml library: /home/shiva/anaconda3/envs/my_env/lib/python3.6/site-packages/ruamel/yaml/__init__.py
2020-01-24 11:39:23,271 [DEBUG]  Created a new lock for conversation 'USL7D6TK9'
2020-01-24 11:39:23,272 [DEBUG]  Creating a new tracker for id 'USL7D6TK9'.
2020-01-24 11:39:23,285 [DEBUG]  Received user message 'bye' with intent '{'name': 'goodbye', 'confidence': 0.49229199368390303}' and entities '[]'
2020-01-24 11:39:23,285 [DEBUG]  Logged UserUtterance - tracker now has 2 events
2020-01-24 11:39:23,615 [DEBUG]  Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_goodbye': 1.0}]
2020-01-24 11:39:23,615 [DEBUG]  There is a memorised next action '11'
2020-01-24 11:39:23,615 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-01-24 11:39:23,616 [DEBUG]  There is no active form
2020-01-24 11:39:23,616 [DEBUG]  Predicted next action using policy_1_MemoizationPolicy
2020-01-24 11:39:23,616 [DEBUG]  Predicted next action 'utter_goodbye' with confidence 1.00.
2020-01-24 11:39:23,616 [DEBUG]  Action 'utter_goodbye' ended with events '['BotUttered(text: Bye, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2020-01-24 11:39:23,909 [DEBUG]  Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_goodbye': 1.0}, {'prev_utter_goodbye': 1.0, 'intent_goodbye': 1.0}]
2020-01-24 11:39:23,909 [DEBUG]  There is a memorised next action '0'
2020-01-24 11:39:23,909 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-01-24 11:39:23,909 [DEBUG]  There is no active form
2020-01-24 11:39:23,910 [DEBUG]  Predicted next action using policy_1_MemoizationPolicy
2020-01-24 11:39:23,910 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2020-01-24 11:39:23,910 [DEBUG]  Action 'action_listen' ended with events '[]'
2020-01-24 11:39:23,911 [DEBUG]  Deleted lock for conversation 'USL7D6TK9' (unused)
2020-01-24 12:02:52,181 [INFO ]  Starting Rasa server on http://localhost:5005
2020-01-24 12:03:23,750 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
